// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqrxrqB7Ljtw-8yw5J5hqIrGiVXINYoHY',
    appId: '1:782705023008:web:1fb890f20ac6bf0bb50445',
    messagingSenderId: '782705023008',
    projectId: 'heywayapp-d7811',
    authDomain: 'heywayapp-d7811.firebaseapp.com',
    storageBucket: 'heywayapp-d7811.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVsMsR-Yx_4F217p4TbxUz9qiK2Drb0e4',
    appId: '1:782705023008:android:c5208d28dbcbf018b50445',
    messagingSenderId: '782705023008',
    projectId: 'heywayapp-d7811',
    storageBucket: 'heywayapp-d7811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqry3WUHRKySQ8G5-O8LlFGkx0pI3HD0',
    appId: '1:782705023008:ios:d509743bdfb442b2b50445',
    messagingSenderId: '782705023008',
    projectId: 'heywayapp-d7811',
    storageBucket: 'heywayapp-d7811.firebasestorage.app',
    iosBundleId: 'com.example.heyway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqry3WUHRKySQ8G5-O8LlFGkx0pI3HD0',
    appId: '1:782705023008:ios:d509743bdfb442b2b50445',
    messagingSenderId: '782705023008',
    projectId: 'heywayapp-d7811',
    storageBucket: 'heywayapp-d7811.firebasestorage.app',
    iosBundleId: 'com.example.heyway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqrxrqB7Ljtw-8yw5J5hqIrGiVXINYoHY',
    appId: '1:782705023008:web:468b6d98b5cc9abbb50445',
    messagingSenderId: '782705023008',
    projectId: 'heywayapp-d7811',
    authDomain: 'heywayapp-d7811.firebaseapp.com',
    storageBucket: 'heywayapp-d7811.firebasestorage.app',
  );
}
